export const theme = {
  colors: {
    background: "#FFFCF8",
    subtle: "#FFFDF9",
    foreground: "#1F2A44",
    gray: "#6B7280",
    card: "#FFFFFF",
    primary: "#DCCCFF",
    lavender: "#DCCCFF",
    reviewPink: "#FFB6C9",
    trustMint: "#BDEECF",
    softPeach: "#FFD785",
    border: "#F1E8DD",
    trustVeryHigh: "#9B8AFB",
    trustHigh: "#8FD8B5",
    trustCaution: "#F6C56F",
    trustConcern: "#F29A7E",
    trustVeryConcern: "#E989B5",
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 24,
  },
} as const
