import type {
  AdminUser,
  AnalysisHistoryItem,
  CompareHospital,
  HospitalCategory,
  LoginHistory,
  MyReport,
  NotificationItem,
  NotificationSettings,
  RecentViewedHospital,
  SavedHospital,
  UserInsight,
} from "@/lib/types"

export const categoryLabels: Record<HospitalCategory, string> = {
  derma: "피부과",
  eye: "안과",
  dental: "치과",
}

export function formatStars(rating = 0) {
  const safeRating = Math.max(0, Math.min(5, Math.round(rating)))
  return `${"★".repeat(safeRating)}${"☆".repeat(5 - safeRating)}`
}

export const mockAnalysisHistory: AnalysisHistoryItem[] = [
  {
    id: "101",
    hospitalName: "연세밝은피부과",
    category: "derma",
    score: 86,
    foreignerFriendlyScore: 80,
    createdAt: "2026.06.18",
    analyzedAt: "2026.06.18",
    trustScore: 86,
    trustLevel: "신뢰 가능",
    adSuspicionScore: 18,
    adSuspicionLevel: "낮음",
    infoCompletenessScore: 91,
    globalAccessRating: 4,
    reviewCount: 124,
  },
  {
    id: "102",
    hospitalName: "화이트치과의원",
    category: "dental",
    score: 78,
    foreignerFriendlyScore: 60,
    createdAt: "2026.06.15",
    analyzedAt: "2026.06.15",
    trustScore: 78,
    trustLevel: "신뢰 가능",
    adSuspicionScore: 32,
    adSuspicionLevel: "주의",
    infoCompletenessScore: 84,
    globalAccessRating: 3,
    reviewCount: 98,
  },
  {
    id: "103",
    hospitalName: "밝은눈안과 강남점",
    category: "eye",
    score: 91,
    foreignerFriendlyScore: 100,
    createdAt: "2026.06.11",
    analyzedAt: "2026.06.11",
    trustScore: 91,
    trustLevel: "매우 신뢰",
    adSuspicionScore: 12,
    adSuspicionLevel: "낮음",
    infoCompletenessScore: 95,
    globalAccessRating: 5,
    reviewCount: 212,
  },
  {
    id: "104",
    hospitalName: "스마일치과",
    category: "dental",
    score: 69,
    foreignerFriendlyScore: 40,
    createdAt: "2026.06.05",
    analyzedAt: "2026.06.05",
    trustScore: 69,
    trustLevel: "주의",
    adSuspicionScore: 46,
    adSuspicionLevel: "높음",
    infoCompletenessScore: 72,
    globalAccessRating: 2,
    reviewCount: 64,
  },
]

export const mockSavedHospitals: SavedHospital[] = [
  {
    id: 201,
    hospitalName: "연세밝은피부과",
    category: "derma",
    address: "서울 강남구 테헤란로 12",
    trustScore: 86,
    trustLevel: "신뢰 가능",
    adSuspicionScore: 18,
    adSuspicionLevel: "낮음",
    infoCompletenessScore: 91,
    globalAccessRating: 4,
    savedAt: "2026.06.18",
    lastAnalyzedAt: "2026.06.18",
  },
  {
    id: 202,
    hospitalName: "화이트치과의원",
    category: "dental",
    address: "서울 서초구 서초대로 77",
    trustScore: 78,
    trustLevel: "신뢰 가능",
    adSuspicionScore: 32,
    adSuspicionLevel: "주의",
    infoCompletenessScore: 84,
    globalAccessRating: 3,
    savedAt: "2026.06.15",
    lastAnalyzedAt: "2026.06.15",
  },
  {
    id: 203,
    hospitalName: "밝은눈안과 강남점",
    category: "eye",
    address: "서울 강남구 강남대로 312",
    trustScore: 91,
    trustLevel: "매우 신뢰",
    adSuspicionScore: 12,
    adSuspicionLevel: "낮음",
    infoCompletenessScore: 95,
    globalAccessRating: 5,
    savedAt: "2026.06.11",
    lastAnalyzedAt: "2026.06.11",
  },
  {
    id: 204,
    hospitalName: "스마일치과",
    category: "dental",
    address: "서울 마포구 양화로 21",
    trustScore: 69,
    trustLevel: "주의",
    adSuspicionScore: 46,
    adSuspicionLevel: "높음",
    infoCompletenessScore: 72,
    globalAccessRating: 2,
    savedAt: "2026.06.05",
    lastAnalyzedAt: "2026.06.05",
  },
]

export const mockCompareHospitals: CompareHospital[] = mockSavedHospitals.map((hospital, index) => ({
  ...hospital,
  reviewCount: [124, 98, 212, 64][index] ?? 60,
  recentReviewRatio: [72, 58, 81, 44][index] ?? 50,
  negativeReviewRatio: [8, 15, 5, 22][index] ?? 12,
  dentalMetrics: hospital.category === "dental" ? {
    overtreatmentSuspicion: hospital.id === 202 ? "낮음" : "주의",
    priceMentionLevel: "보통",
    explanationKindness: "좋음",
    revisitReviewLevel: "보통",
    painMentionLevel: "낮음",
    waitingMentionLevel: "보통",
  } : undefined,
  eyeMetrics: hospital.category === "eye" ? {
    examExplanation: "상세함",
    surgeryReviewTrust: "높음",
    aftercareMention: "충분",
    equipmentInfo: "좋음",
    waitingMentionLevel: "낮음",
    consultationSatisfaction: "높음",
  } : undefined,
  dermatologyMetrics: hospital.category === "derma" ? {
    treatmentEffectReview: "구체적",
    adReviewSuspicion: "낮음",
    eventPhraseLevel: "낮음",
    consultationKindness: "좋음",
    revisitReviewLevel: "높음",
    beforeAfterDetail: "충분",
  } : undefined,
}))

export const mockReports: MyReport[] = [
  {
    id: 301,
    targetType: "review",
    hospitalName: "화이트치과의원",
    reason: "광고성 리뷰 의심",
    status: "REVIEWING",
    createdAt: "2026.06.17",
  },
  {
    id: 302,
    targetType: "hospital",
    hospitalName: "밝은눈안과 강남점",
    reason: "홈페이지 링크 오류",
    status: "COMPLETED",
    createdAt: "2026.06.12",
    adminReply: "제보해주신 링크를 확인하고 수정했습니다.",
  },
]

export const mockNotifications: NotificationItem[] = [
  {
    id: 401,
    title: "분석 결과가 준비되었어요.",
    message: "연세밝은피부과 분석 리포트를 확인해보세요.",
    type: "analysis_done",
    isRead: false,
    createdAt: "2026.06.18",
    link: "/mypage/history",
    actionLabel: "결과 보기",
  },
  {
    id: 402,
    title: "검토가 완료됐어요.",
    message: "홈페이지 링크 오류 검토에 관리자 답변이 등록됐어요.",
    type: "review_resolved",
    isRead: false,
    createdAt: "2026.06.17",
    link: "/mypage/reports",
    actionLabel: "검토 내역 보기",
  },
  {
    id: 403,
    title: "저장한 병원 정보가 업데이트되었어요.",
    message: "밝은눈안과의 예약 링크 정보가 갱신됐어요.",
    type: "info_updated",
    isRead: true,
    createdAt: "2026.06.15",
    link: "/mypage/saved",
    actionLabel: "확인하기",
  },
]

export const mockNotificationSettings: NotificationSettings = {
  analysisCompleted: true,
  reportResult: true,
  savedHospitalUpdated: true,
  securityAlert: true,
  marketing: false,
}

export const mockRecentViewedHospitals: RecentViewedHospital[] = [
  {
    id: 501,
    hospitalName: "연세밝은피부과",
    category: "derma",
    address: "서울 강남구 테헤란로 12",
    viewedAt: "2026.06.18",
    trustLevel: "신뢰 가능",
    globalAccessRating: 4,
  },
  {
    id: 502,
    hospitalName: "화이트치과의원",
    category: "dental",
    address: "서울 서초구 서초대로 77",
    viewedAt: "2026.06.16",
    trustLevel: "신뢰 가능",
    globalAccessRating: 3,
  },
]

export const mockUserInsight: UserInsight = {
  mostAnalyzedCategory: "dental",
  frequentArea: "서울 강남·서초",
  savedHospitalAverageTrustLevel: "신뢰 가능",
  mainDecisionFactors: ["리뷰 신뢰도", "외국인 방문 편의도", "광고 의심도"],
  summary: "최근 치과를 가장 많이 분석했고, 광고 의심도가 낮은 병원을 주로 저장했어요.",
}

export const mockLoginHistory: LoginHistory[] = [
  {
    id: 601,
    loggedInAt: "2026.06.18 14:20",
    method: "이메일",
    device: "Chrome · Linux",
    location: "Seoul, KR",
  },
  {
    id: 602,
    loggedInAt: "2026.06.17 09:12",
    method: "Google",
    device: "Mobile Safari",
    location: "Seoul, KR",
  },
]

export const mockAdminUsers: AdminUser[] = [
  {
    id: 1,
    email: "jung@example.com",
    name: "조정화",
    nickname: "필토리왕",
    role: "USER",
    status: "ACTIVE",
    provider: "local",
    emailVerified: true,
    hasPassword: true,
    createdAt: "2026.05.10",
    lastLoginAt: "2026.06.18",
    analysisCount: 12,
    savedHospitalCount: 4,
    reportCount: 2,
    memo: "병원 비교 기능을 자주 사용합니다.",
  },
  {
    id: 2,
    email: "admin@filtory.local",
    name: "관리자",
    nickname: "Filtory Admin",
    role: "ADMIN",
    status: "ACTIVE",
    provider: "google",
    emailVerified: true,
    createdAt: "2026.04.01",
    lastLoginAt: "2026.06.17",
    analysisCount: 3,
    savedHospitalCount: 1,
    reportCount: 0,
  },
]
