create table if not exists public.analysis_usage_logs (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  analysis_result_id bigint not null references public.analysis_results(id) on delete cascade,
  usage_type varchar(30) not null,
  period_key varchar(7) not null,
  charged_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  constraint analysis_usage_logs_unique_member_analysis
    unique (member_id, analysis_result_id),
  constraint analysis_usage_logs_usage_type_check
    check (usage_type in ('FREE_BASE', 'PLUS', 'REWARDED', 'ADMIN_GRANTED'))
);

create index if not exists idx_analysis_usage_logs_member_period
on public.analysis_usage_logs(member_id, period_key);
