-- User-submitted hospital enrichment suggestions.
-- Keep public.hospitals as verified/shared hospital data.

create table if not exists public.hospital_enrichment_suggestions (
  id bigint generated by default as identity primary key,

  hospital_id bigint not null
    references public.hospitals(id) on delete cascade,

  analysis_request_id bigint
    references public.analysis_requests(id) on delete set null,

  source_member_id bigint
    references public.members(id) on delete set null,

  source_type varchar(30) not null default 'user_input',
  status varchar(20) not null default 'pending',

  suggested_english_name varchar(255),
  suggested_homepage_url text,
  suggested_has_english_info boolean,
  suggested_has_english_reviews boolean,
  suggested_has_photos boolean,

  reviewer_member_id bigint
    references public.members(id) on delete set null,

  reviewed_at timestamp with time zone,
  reject_reason text,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint hospital_enrichment_suggestions_status_check
    check (status in ('pending', 'approved', 'rejected', 'applied')),

  constraint hospital_enrichment_suggestions_source_type_check
    check (source_type in ('user_input', 'admin', 'provider', 'ocr', 'analysis')),

  constraint hospital_enrichment_suggestions_homepage_url_check
    check (
      suggested_homepage_url is null
      or suggested_homepage_url ~* '^https?://[^[:space:]/]+'
    ),

  constraint hospital_enrichment_suggestions_has_any_value_check
    check (
      suggested_english_name is not null
      or suggested_homepage_url is not null
      or suggested_has_english_info is not null
      or suggested_has_english_reviews is not null
      or suggested_has_photos is not null
    )
);

drop trigger if exists trg_hospital_enrichment_suggestions_updated_at
on public.hospital_enrichment_suggestions;

create trigger trg_hospital_enrichment_suggestions_updated_at
before update on public.hospital_enrichment_suggestions
for each row
execute function public.set_updated_at();

create index if not exists idx_hospital_enrichment_suggestions_hospital_status
on public.hospital_enrichment_suggestions(hospital_id, status);

create index if not exists idx_hospital_enrichment_suggestions_source_member
on public.hospital_enrichment_suggestions(source_member_id);

create index if not exists idx_hospital_enrichment_suggestions_analysis_request
on public.hospital_enrichment_suggestions(analysis_request_id);

create index if not exists idx_hospital_enrichment_suggestions_created_at
on public.hospital_enrichment_suggestions(created_at desc);

-- Apply an approved suggestion to the verified hospital row by replacing
-- :suggestion_id with the selected hospital_enrichment_suggestions.id.
--
-- update public.hospitals as h
-- set
--   english_name = coalesce(h.english_name, s.suggested_english_name),
--   homepage_url = coalesce(h.homepage_url, s.suggested_homepage_url),
--   has_english_info = h.has_english_info or coalesce(s.suggested_has_english_info, false),
--   has_english_reviews = h.has_english_reviews or coalesce(s.suggested_has_english_reviews, false),
--   has_photos = h.has_photos or coalesce(s.suggested_has_photos, false)
-- from public.hospital_enrichment_suggestions as s
-- where s.id = :suggestion_id
--   and s.hospital_id = h.id
--   and s.status = 'approved';
--
-- update public.hospital_enrichment_suggestions
-- set status = 'applied'
-- where id = :suggestion_id
--   and status = 'approved';
