-- Admin review moderation and hospital management support.
-- Existing tables used:
--   public.reviews
--   public.analysis_results
--   public.review_reports
--   public.hospitals
--   public.members

create table if not exists public.admin_review_moderation_cases (
  id bigint generated by default as identity primary key,

  hospital_id bigint
    references public.hospitals(id) on delete cascade,

  review_id bigint
    references public.reviews(id) on delete cascade,

  analysis_result_id bigint
    references public.analysis_results(id) on delete cascade,

  review_report_id bigint
    references public.review_reports(id) on delete set null,

  case_type varchar(50) not null,
  status varchar(30) not null default 'pending',
  priority varchar(20) not null default 'normal',

  reason text,
  score_snapshot jsonb not null default '{}'::jsonb,

  assigned_admin_member_id bigint
    references public.members(id) on delete set null,

  resolved_admin_member_id bigint
    references public.members(id) on delete set null,

  admin_memo text,
  resolved_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint admin_review_moderation_cases_type_check
    check (case_type in (
      'ad_suspicion',
      'repetition_pattern',
      'inappropriate_content',
      'user_report',
      'wrong_hospital_info',
      'manual_review',
      'other'
    )),

  constraint admin_review_moderation_cases_status_check
    check (status in (
      'pending',
      'reviewing',
      'resolved',
      'rejected',
      'ignored',
      'hidden'
    )),

  constraint admin_review_moderation_cases_priority_check
    check (priority in ('low', 'normal', 'high', 'urgent')),

  constraint admin_review_moderation_cases_has_target_check
    check (
      review_id is not null
      or analysis_result_id is not null
      or review_report_id is not null
    )
);

drop trigger if exists trg_admin_review_moderation_cases_updated_at
on public.admin_review_moderation_cases;

create trigger trg_admin_review_moderation_cases_updated_at
before update on public.admin_review_moderation_cases
for each row
execute function public.set_updated_at();

create index if not exists idx_admin_review_moderation_cases_status_created_at
on public.admin_review_moderation_cases(status, created_at desc);

create index if not exists idx_admin_review_moderation_cases_type_status
on public.admin_review_moderation_cases(case_type, status);

create index if not exists idx_admin_review_moderation_cases_hospital_id
on public.admin_review_moderation_cases(hospital_id);

create index if not exists idx_admin_review_moderation_cases_review_id
on public.admin_review_moderation_cases(review_id);

create index if not exists idx_admin_review_moderation_cases_analysis_result_id
on public.admin_review_moderation_cases(analysis_result_id);

create index if not exists idx_admin_review_moderation_cases_review_report_id
on public.admin_review_moderation_cases(review_report_id);

create index if not exists idx_admin_review_moderation_cases_assigned_admin
on public.admin_review_moderation_cases(assigned_admin_member_id);

create unique index if not exists uq_admin_review_moderation_cases_open_review_type
on public.admin_review_moderation_cases(review_id, case_type)
where review_id is not null
  and status in ('pending', 'reviewing');

create unique index if not exists uq_admin_review_moderation_cases_open_analysis_type
on public.admin_review_moderation_cases(analysis_result_id, case_type)
where analysis_result_id is not null
  and status in ('pending', 'reviewing');

alter table public.admin_review_moderation_cases
enable row level security;

revoke all
on table public.admin_review_moderation_cases
from anon, authenticated;

revoke all
on sequence public.admin_review_moderation_cases_id_seq
from anon, authenticated;

alter table public.hospitals
add column if not exists admin_status varchar(30) not null default 'active',
add column if not exists admin_memo text,
add column if not exists verified_by bigint
  references public.members(id) on delete set null,
add column if not exists verified_at timestamp with time zone,
add column if not exists hidden_by bigint
  references public.members(id) on delete set null,
add column if not exists hidden_at timestamp with time zone;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'hospitals_admin_status_check'
      and conrelid = 'public.hospitals'::regclass
  ) then
    alter table public.hospitals
    add constraint hospitals_admin_status_check
      check (admin_status in ('active', 'needs_review', 'hidden', 'archived'));
  end if;
end $$;

create index if not exists idx_hospitals_admin_status_updated_at
on public.hospitals(admin_status, updated_at desc);

create index if not exists idx_hospitals_verified_by
on public.hospitals(verified_by);

create index if not exists idx_hospitals_hidden_by
on public.hospitals(hidden_by);
