-- Supabase SQL Editor에서 수동 실행하는 관리자 공지사항/FAQ 스키마입니다.
-- 이 파일 추가만으로 애플리케이션 API가 연결되지는 않습니다.

create table if not exists public.admin_notices (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  content text not null,
  status varchar(20) not null default 'DRAFT',
  pinned boolean not null default false,
  published_at timestamp with time zone,
  created_by bigint references public.members(id) on delete set null,
  updated_by bigint references public.members(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint admin_notices_status_check
    check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

create index if not exists idx_admin_notices_status_published
on public.admin_notices(status, published_at desc);

create table if not exists public.admin_faqs (
  id bigint generated by default as identity primary key,
  category varchar(50) not null default 'GENERAL',
  question varchar(300) not null,
  answer text not null,
  status varchar(20) not null default 'DRAFT',
  sort_order integer not null default 0,
  published_at timestamp with time zone,
  created_by bigint references public.members(id) on delete set null,
  updated_by bigint references public.members(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint admin_faqs_status_check
    check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  constraint admin_faqs_sort_order_check
    check (sort_order >= 0)
);

create index if not exists idx_admin_faqs_status_sort
on public.admin_faqs(status, sort_order, published_at desc);
