-- Existing member_saved_hospitals is the canonical favorite_hospitals relation.
-- Keep existing data while extending the supported hospital categories.
ALTER TABLE public.hospitals DROP CONSTRAINT IF EXISTS hospitals_category_check;
ALTER TABLE public.hospitals ADD CONSTRAINT hospitals_category_check
  CHECK (category IN ('dermatology', 'ophthalmology', 'dentistry', 'orthopedics'));

-- Recent hospital history used by /api/recent-hospitals.
CREATE TABLE IF NOT EXISTS public.member_recent_viewed_hospitals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  hospital_id bigint NOT NULL REFERENCES public.hospitals(id) ON DELETE CASCADE,
  analysis_result_id bigint REFERENCES public.analysis_results(id) ON DELETE SET NULL,
  viewed_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT member_recent_viewed_hospitals_member_hospital_unique
    UNIQUE (member_id, hospital_id)
);

CREATE INDEX IF NOT EXISTS idx_member_recent_viewed_hospitals_member_viewed_at
ON public.member_recent_viewed_hospitals(member_id, viewed_at DESC);

CREATE INDEX IF NOT EXISTS idx_member_recent_viewed_hospitals_hospital_id
ON public.member_recent_viewed_hospitals(hospital_id);
