-- =========================================
-- Filtory web app feature support
-- Base schema reference:
--   public.members, public.reviews, and public.admin_audit_logs already exist
--   in docs/database/schema.sql.
-- This migration adds only columns/tables required by the app UI features.
-- =========================================

alter table public.reviews
add column if not exists rating int,
add column if not exists visit_date date,
add column if not exists updated_at timestamp with time zone not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reviews_rating_check'
  ) then
    alter table public.reviews
    add constraint reviews_rating_check
    check (rating is null or (rating >= 1 and rating <= 5));
  end if;
end;
$$;

drop trigger if exists trg_reviews_updated_at on public.reviews;

create trigger trg_reviews_updated_at
before update on public.reviews
for each row
execute function public.set_updated_at();

create index if not exists idx_reviews_visit_date
on public.reviews(visit_date);

create table if not exists public.member_withdrawals (
  id bigint generated by default as identity primary key,

  member_id bigint references public.members(id) on delete set null,

  reason text,
  request_ip varchar(100),
  user_agent text,

  created_at timestamp with time zone not null default now()
);

create index if not exists idx_member_withdrawals_member_id
on public.member_withdrawals(member_id);

create table if not exists public.admin_member_memos (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,
  admin_member_id bigint references public.members(id) on delete set null,

  memo text not null,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

drop trigger if exists trg_admin_member_memos_updated_at on public.admin_member_memos;

create trigger trg_admin_member_memos_updated_at
before update on public.admin_member_memos
for each row
execute function public.set_updated_at();

create index if not exists idx_admin_member_memos_member_id
on public.admin_member_memos(member_id);

create index if not exists idx_admin_member_memos_admin_member_id
on public.admin_member_memos(admin_member_id);

create table if not exists public.member_sanctions (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,
  admin_member_id bigint references public.members(id) on delete set null,

  sanction_type varchar(30) not null,
  reason text,

  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),

  constraint member_sanctions_type_check
    check (sanction_type in ('warning', 'disabled', 'blocked', 'reactivated'))
);

create index if not exists idx_member_sanctions_member_id
on public.member_sanctions(member_id);

create index if not exists idx_member_sanctions_admin_member_id
on public.member_sanctions(admin_member_id);

create index if not exists idx_member_sanctions_type
on public.member_sanctions(sanction_type);
