-- Inquiry attachments and member notification center support.
-- Run this once in the Supabase SQL editor before deploying the app code.
-- Attachments use a private Supabase Storage bucket and are downloaded through backend-main after auth checks.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'inquiry-attachments',
  'inquiry-attachments',
  false,
  5242880,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'text/plain',
    'text/csv',
    'application/csv',
    'application/vnd.ms-excel'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.inquiries
add column if not exists attachment_path text,
add column if not exists attachment_file_name varchar(255),
add column if not exists attachment_content_type varchar(100),
add column if not exists attachment_size integer;

create index if not exists idx_inquiries_attachment_path
on public.inquiries(attachment_path)
where attachment_path is not null;

create table if not exists public.member_notifications (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  notification_type varchar(30) not null,
  title varchar(255) not null,
  message text not null,
  link_url text,
  metadata_json jsonb,
  is_read boolean not null default false,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

alter table public.member_notifications
drop constraint if exists member_notifications_type_check;

alter table public.member_notifications
add constraint member_notifications_type_check
check (notification_type in (
  'analysis',
  'inquiry',
  'report',
  'saved_hospital',
  'security',
  'marketing',
  'system'
));

alter table public.member_notifications
add column if not exists metadata_json jsonb;

create index if not exists idx_member_notifications_member_created_at
on public.member_notifications(member_id, created_at desc);

create index if not exists idx_member_notifications_member_unread
on public.member_notifications(member_id, is_read)
where is_read is false;

create index if not exists idx_member_notifications_type_created_at
on public.member_notifications(notification_type, created_at desc);

alter table public.member_notifications enable row level security;

revoke all
on table public.member_notifications
from anon, authenticated;

revoke all
on sequence public.member_notifications_id_seq
from anon, authenticated;
