-- =========================================
-- Filtory review media, comments, and reactions
-- Base schema reference:
--   public.reviews already exists in docs/database/schema.sql.
--   public.members already exists in docs/database/schema.sql.
-- This migration only adds tables that are not present in the base schema.
-- =========================================

create table if not exists public.review_images (
  id bigint generated by default as identity primary key,

  review_id bigint not null references public.reviews(id) on delete cascade,

  image_url text not null,
  alt_text varchar(255),
  sort_order int not null default 0,

  created_at timestamp with time zone not null default now()
);

create index if not exists idx_review_images_review_id
on public.review_images(review_id);

create table if not exists public.review_comments (
  id bigint generated by default as identity primary key,

  review_id bigint not null references public.reviews(id) on delete cascade,
  member_id bigint references public.members(id) on delete set null,
  parent_comment_id bigint references public.review_comments(id) on delete cascade,

  content text not null,
  deleted_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

drop trigger if exists trg_review_comments_updated_at on public.review_comments;

create trigger trg_review_comments_updated_at
before update on public.review_comments
for each row
execute function public.set_updated_at();

create index if not exists idx_review_comments_review_id
on public.review_comments(review_id);

create index if not exists idx_review_comments_member_id
on public.review_comments(member_id);

create index if not exists idx_review_comments_parent_comment_id
on public.review_comments(parent_comment_id);

create table if not exists public.review_comment_reactions (
  id bigint generated by default as identity primary key,

  comment_id bigint not null references public.review_comments(id) on delete cascade,
  member_id bigint references public.members(id) on delete cascade,
  reaction_type varchar(20) not null,

  created_at timestamp with time zone not null default now(),

  constraint review_comment_reactions_type_check
    check (reaction_type in ('like', 'dislike')),

  constraint review_comment_reactions_member_comment_unique
    unique (comment_id, member_id)
);

create index if not exists idx_review_comment_reactions_comment_id
on public.review_comment_reactions(comment_id);

create index if not exists idx_review_comment_reactions_member_id
on public.review_comment_reactions(member_id);
