-- Filtory review and mypage persistence
-- Prerequisites: docs/database/schema.sql
-- Also apply: docs/database/20260622_member_admin_saved_hospitals.sql

-- 1. Review fields used by the hospital detail UI.
alter table public.reviews
add column if not exists rating int,
add column if not exists visit_date date,
add column if not exists updated_at timestamp with time zone not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'reviews_rating_check'
  ) then
    alter table public.reviews
    add constraint reviews_rating_check
    check (rating is null or (rating >= 1 and rating <= 5));
  end if;
end;
$$;

drop trigger if exists trg_reviews_updated_at on public.reviews;
create trigger trg_reviews_updated_at
before update on public.reviews
for each row
execute function public.set_updated_at();

create index if not exists idx_reviews_visit_date
on public.reviews(visit_date);

-- Image binaries belong in Supabase Storage. This table stores their URLs and display order.
create table if not exists public.review_images (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  image_url text not null,
  alt_text varchar(255),
  sort_order int not null default 0,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_review_images_review_id
on public.review_images(review_id);

create table if not exists public.review_comments (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  member_id bigint references public.members(id) on delete set null,
  parent_comment_id bigint references public.review_comments(id) on delete cascade,
  content text not null,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

drop trigger if exists trg_review_comments_updated_at on public.review_comments;
create trigger trg_review_comments_updated_at
before update on public.review_comments
for each row
execute function public.set_updated_at();

create index if not exists idx_review_comments_review_id
on public.review_comments(review_id);
create index if not exists idx_review_comments_member_id
on public.review_comments(member_id);
create index if not exists idx_review_comments_parent_comment_id
on public.review_comments(parent_comment_id);

create table if not exists public.review_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.review_comments(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  reaction_type varchar(20) not null,
  created_at timestamp with time zone not null default now(),
  constraint review_comment_reactions_type_check
    check (reaction_type in ('like', 'dislike')),
  constraint review_comment_reactions_member_comment_unique
    unique (comment_id, member_id)
);

create index if not exists idx_review_comment_reactions_comment_id
on public.review_comment_reactions(comment_id);

-- 2. Notification center and per-member delivery preferences.
create table if not exists public.member_notifications (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  notification_type varchar(30) not null,
  title varchar(255) not null,
  message text not null,
  link_url text,
  is_read boolean not null default false,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint member_notifications_type_check
    check (notification_type in ('analysis', 'report', 'saved_hospital', 'security', 'marketing'))
);

create index if not exists idx_member_notifications_member_created_at
on public.member_notifications(member_id, created_at desc);
create index if not exists idx_member_notifications_member_unread
on public.member_notifications(member_id, is_read)
where is_read is false;

create table if not exists public.member_notification_settings (
  member_id bigint primary key references public.members(id) on delete cascade,
  analysis_completed boolean not null default true,
  report_result boolean not null default true,
  saved_hospital_updated boolean not null default true,
  security_alert boolean not null default true,
  marketing boolean not null default false,
  language varchar(10) not null default 'ko',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint member_notification_settings_language_check
    check (language in ('ko', 'en'))
);

drop trigger if exists trg_member_notification_settings_updated_at on public.member_notification_settings;
create trigger trg_member_notification_settings_updated_at
before update on public.member_notification_settings
for each row
execute function public.set_updated_at();

-- 3. Account-based recent hospital history.
create table if not exists public.member_recent_viewed_hospitals (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  analysis_result_id bigint references public.analysis_results(id) on delete set null,
  viewed_at timestamp with time zone not null default now(),
  constraint member_recent_viewed_hospitals_member_hospital_unique
    unique (member_id, hospital_id)
);

create index if not exists idx_member_recent_viewed_hospitals_member_viewed_at
on public.member_recent_viewed_hospitals(member_id, viewed_at desc);

-- 4. Login/security history. Location is optional because IP geolocation is not implemented yet.
create table if not exists public.member_login_history (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  login_method varchar(30) not null,
  request_ip varchar(100),
  user_agent text,
  device varchar(255),
  location varchar(255),
  logged_in_at timestamp with time zone not null default now(),
  constraint member_login_history_method_check
    check (login_method in ('local', 'google', 'kakao', 'naver'))
);

create index if not exists idx_member_login_history_member_logged_in_at
on public.member_login_history(member_id, logged_in_at desc);

-- 5. Email verification. Store only a SHA-256 token hash, never the raw token.
create table if not exists public.email_verification_tokens (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,
  request_ip varchar(100),
  user_agent text,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_email_verification_tokens_member_id
on public.email_verification_tokens(member_id);
create index if not exists idx_email_verification_tokens_expires_at
on public.email_verification_tokens(expires_at);
