-- Filtory member/admin API support
-- Apply this migration in Supabase SQL Editor after the existing schema migrations.

-- 1. Persist the four account states already exposed by the frontend.
alter table public.members
add column if not exists status varchar(30);

update public.members
set status = case
  when deleted_at is not null then 'withdrawn'
  when active is false then 'suspended'
  else 'active'
end
where status is null;

alter table public.members
alter column status set default 'active';

alter table public.members
alter column status set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'members_status_check'
  ) then
    alter table public.members
    add constraint members_status_check
    check (status in ('active', 'suspended', 'withdrawn', 'dormant'));
  end if;
end;
$$;

create index if not exists idx_members_status
on public.members(status);

-- 2. Nicknames are unique after trimming and case normalization.
-- Resolve any rows returned by this diagnostic before creating the unique index.
select lower(btrim(nickname)) as normalized_nickname, array_agg(id order by id) as member_ids
from public.members
where nickname is not null and btrim(nickname) <> ''
group by lower(btrim(nickname))
having count(*) > 1;

create unique index if not exists idx_members_nickname_normalized_unique
on public.members (lower(btrim(nickname)))
where nickname is not null and btrim(nickname) <> '';

-- 3. Save a hospital per account, optionally pinning the result that was shown when saved.
create table if not exists public.member_saved_hospitals (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  analysis_result_id bigint references public.analysis_results(id) on delete set null,

  saved_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint member_saved_hospitals_member_hospital_unique
    unique (member_id, hospital_id)
);

drop trigger if exists trg_member_saved_hospitals_updated_at on public.member_saved_hospitals;

create trigger trg_member_saved_hospitals_updated_at
before update on public.member_saved_hospitals
for each row
execute function public.set_updated_at();

create index if not exists idx_member_saved_hospitals_member_saved_at
on public.member_saved_hospitals(member_id, saved_at desc);

create index if not exists idx_member_saved_hospitals_hospital_id
on public.member_saved_hospitals(hospital_id);

create index if not exists idx_member_saved_hospitals_analysis_result_id
on public.member_saved_hospitals(analysis_result_id)
where analysis_result_id is not null;

with ranked_duplicates as (
  select
    id,
    nickname,
    row_number() over (
      partition by lower(btrim(nickname))
      order by created_at asc nulls last, id asc
    ) as row_num
  from public.members
  where nickname is not null
    and btrim(nickname) <> ''
)
update public.members as m
set nickname = btrim(m.nickname) || '-dup-' || m.id
from ranked_duplicates as d
where m.id = d.id
  and d.row_num > 1;