begin;

-- Free is now an implicit entitlement. Keep member_subscriptions for paid/test/admin grants only.
drop trigger if exists trg_members_create_default_subscription on public.members;
drop function if exists public.create_default_free_subscription();

delete from public.member_subscriptions ms
using public.subscription_plans sp
where ms.plan_id = sp.id
  and sp.plan_code = 'free'
  and ms.payment_provider is null
  and ms.payment_customer_id is null
  and ms.payment_subscription_id is null;

alter table public.subscription_plans drop constraint if exists subscription_plans_code_check;

update public.subscription_plans
set plan_code = 'plus',
    plan_name = 'Filtory Plus',
    monthly_price = 4900,
    monthly_analysis_limit = 30,
    description = '월 상세 분석 30회 및 스폰서 콘텐츠 제거'
where plan_code = 'pro';

update public.subscription_plans
set plan_name = 'Filtory Free',
    monthly_price = 0,
    monthly_analysis_limit = 5
where plan_code = 'free';

update public.subscription_plans set active = false where plan_code = 'business';

alter table public.subscription_plans
  add column if not exists currency varchar(3) not null default 'KRW',
  add column if not exists billing_interval varchar(20) not null default 'month';

alter table public.subscription_plans add constraint subscription_plans_code_check
  check (plan_code in ('free', 'plus', 'business'));
alter table public.subscription_plans drop constraint if exists subscription_plans_currency_check;
alter table public.subscription_plans add constraint subscription_plans_currency_check check (currency = 'KRW');
alter table public.subscription_plans drop constraint if exists subscription_plans_billing_interval_check;
alter table public.subscription_plans add constraint subscription_plans_billing_interval_check check (billing_interval = 'month');

alter table public.member_subscriptions
  add column if not exists provider_product_id varchar(255),
  add column if not exists provider_purchase_id varchar(255),
  add column if not exists last_verified_at timestamp with time zone,
  add column if not exists grace_period_end timestamp with time zone,
  add column if not exists ended_at timestamp with time zone,
  add column if not exists auto_renew boolean not null default true,
  add column if not exists metadata_json jsonb;

alter table public.member_subscriptions drop constraint if exists member_subscriptions_status_check;
alter table public.member_subscriptions add constraint member_subscriptions_status_check check (status in (
  'pending', 'active', 'trialing', 'cancel_scheduled', 'grace_period', 'past_due', 'on_hold',
  'canceled', 'expired', 'refunded', 'verification_required'
));

drop index if exists public.idx_member_subscriptions_one_active;
create unique index idx_member_subscriptions_one_active
on public.member_subscriptions(member_id)
where status in (
  'active', 'trialing', 'cancel_scheduled', 'grace_period', 'past_due', 'on_hold', 'verification_required'
);

create table if not exists public.billing_products (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.subscription_plans(id),
  provider varchar(30) not null,
  provider_product_id varchar(255) not null,
  amount integer not null,
  currency varchar(3) not null default 'KRW',
  billing_interval varchar(20) not null default 'month',
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint billing_products_provider_check check (provider in ('TOSS', 'GOOGLE_PLAY', 'MOCK')),
  constraint billing_products_amount_check check (amount >= 0),
  constraint billing_products_currency_check check (currency = 'KRW'),
  constraint billing_products_billing_interval_check check (billing_interval = 'month'),
  constraint billing_products_provider_product_unique unique(provider, provider_product_id)
);

create table if not exists public.member_billing_profiles (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  provider varchar(30) not null,
  customer_key varchar(255) not null,
  encrypted_billing_key text,
  encryption_key_version varchar(30),
  status varchar(30) not null default 'pending',
  card_company varchar(100),
  card_number_masked varchar(100),
  authenticated_at timestamp with time zone,
  last_verified_at timestamp with time zone,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint member_billing_profiles_provider_check check (provider in ('TOSS', 'GOOGLE_PLAY', 'MOCK')),
  constraint member_billing_profiles_status_check check (status in ('pending', 'active', 'revoked', 'verification_required')),
  constraint member_billing_profiles_member_provider_unique unique(member_id, provider),
  constraint member_billing_profiles_provider_customer_unique unique(provider, customer_key)
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  subscription_id bigint references public.member_subscriptions(id) on delete set null,
  billing_product_id bigint not null references public.billing_products(id),
  billing_profile_id bigint references public.member_billing_profiles(id) on delete set null,
  provider varchar(30) not null,
  transaction_type varchar(30) not null,
  order_id varchar(255) not null,
  payment_key varchar(255),
  idempotency_key uuid not null,
  amount integer not null,
  currency varchar(3) not null default 'KRW',
  status varchar(30) not null default 'READY',
  requested_at timestamp with time zone not null default now(),
  approved_at timestamp with time zone,
  canceled_at timestamp with time zone,
  failure_code varchar(100),
  failure_message text,
  raw_response_json jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint payment_transactions_provider_check check (provider in ('TOSS', 'GOOGLE_PLAY', 'MOCK')),
  constraint payment_transactions_type_check check (transaction_type in ('INITIAL', 'RENEWAL', 'CANCEL', 'REFUND')),
  constraint payment_transactions_status_check check (status in ('READY', 'IN_PROGRESS', 'DONE', 'FAILED', 'CANCELED', 'PARTIAL_CANCELED', 'ABORTED', 'EXPIRED')),
  constraint payment_transactions_amount_check check (amount >= 0),
  constraint payment_transactions_idempotency_unique unique(idempotency_key),
  constraint payment_transactions_provider_order_unique unique(provider, order_id),
  constraint payment_transactions_provider_payment_unique unique(provider, payment_key)
);

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider varchar(30) not null,
  event_type varchar(100) not null,
  deduplication_key varchar(255) not null,
  payment_key varchar(255),
  processing_status varchar(30) not null default 'RECEIVED',
  payload_json jsonb not null default '{}'::jsonb,
  received_at timestamp with time zone not null default now(),
  processed_at timestamp with time zone,
  error_message text,
  constraint payment_webhook_events_provider_check check (provider in ('TOSS', 'GOOGLE_PLAY', 'MOCK')),
  constraint payment_webhook_events_status_check check (processing_status in ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED')),
  constraint payment_webhook_events_provider_dedup_unique unique(provider, deduplication_key)
);

drop trigger if exists trg_billing_products_updated_at on public.billing_products;
create trigger trg_billing_products_updated_at before update on public.billing_products
for each row execute function public.set_updated_at();
drop trigger if exists trg_member_billing_profiles_updated_at on public.member_billing_profiles;
create trigger trg_member_billing_profiles_updated_at before update on public.member_billing_profiles
for each row execute function public.set_updated_at();
drop trigger if exists trg_payment_transactions_updated_at on public.payment_transactions;
create trigger trg_payment_transactions_updated_at before update on public.payment_transactions
for each row execute function public.set_updated_at();

create index if not exists idx_billing_products_plan_provider_active
on public.billing_products(plan_id, provider) where active = true;
create index if not exists idx_member_billing_profiles_member_id
on public.member_billing_profiles(member_id);
create index if not exists idx_payment_transactions_member_created
on public.payment_transactions(member_id, created_at desc);
create index if not exists idx_payment_transactions_subscription
on public.payment_transactions(subscription_id);
create index if not exists idx_payment_transactions_payment_key
on public.payment_transactions(payment_key) where payment_key is not null;

-- 동일 회원·상품에 결제 가능한 최초 주문이 둘 이상 생기는 경쟁 조건을 DB에서 차단한다.
create unique index if not exists uq_payment_transactions_active_initial
on public.payment_transactions(member_id, billing_product_id, transaction_type)
where transaction_type = 'INITIAL'
  and status in ('READY', 'IN_PROGRESS');
create index if not exists idx_payment_webhook_events_received
on public.payment_webhook_events(received_at desc);

insert into public.billing_products(plan_id, provider, provider_product_id, amount, currency, billing_interval, active)
select id, 'TOSS', 'filtory_plus_monthly', 4900, 'KRW', 'month', true
from public.subscription_plans where plan_code = 'plus'
on conflict(provider, provider_product_id) do update set
  plan_id = excluded.plan_id,
  amount = excluded.amount,
  currency = excluded.currency,
  billing_interval = excluded.billing_interval,
  active = excluded.active;

commit;
