-- Persist chatbot conversations for logged-in members.
-- Anonymous chats remain client-side only and are not written to the database.
CREATE TABLE IF NOT EXISTS public.chatbot_conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  analysis_result_id bigint REFERENCES public.analysis_results(id) ON DELETE SET NULL,
  title varchar(120) NOT NULL DEFAULT 'Filtory 챗봇 대화',
  language varchar(20) NOT NULL DEFAULT 'ko',
  last_message_preview varchar(160),
  message_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chatbot_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.chatbot_conversations(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  role varchar(20) NOT NULL,
  content text NOT NULL,
  source varchar(30),
  model_version varchar(100),
  metadata_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT chatbot_messages_role_check
    CHECK (role IN ('user', 'assistant'))
);

CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_member_updated_at
ON public.chatbot_conversations(member_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_analysis_result_id
ON public.chatbot_conversations(analysis_result_id);

CREATE INDEX IF NOT EXISTS idx_chatbot_messages_conversation_created_at
ON public.chatbot_messages(conversation_id, created_at ASC);
