-- Help center / 1:1 inquiry ticket support.
-- User-facing APIs must use the authenticated member from the token, not URL member ids.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,

  member_id bigint not null
    references public.members(id) on delete cascade,

  category varchar(40) not null,
  sub_category varchar(120),
  title varchar(200) not null,
  content text not null,
  status varchar(30) not null default 'PENDING',

  related_analysis_id bigint
    references public.analysis_requests(id) on delete set null,

  attachment_url text,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint inquiries_category_check
    check (category in (
      'ANALYSIS_RESULT',
      'REVIEW_INPUT',
      'ACCOUNT',
      'PAYMENT',
      'SUGGESTION',
      'OTHER'
    )),

  constraint inquiries_status_check
    check (status in ('PENDING', 'IN_PROGRESS', 'ANSWERED'))
);

create table if not exists public.inquiry_answers (
  id bigint generated by default as identity primary key,

  inquiry_id bigint not null
    references public.inquiries(id) on delete cascade,

  admin_id bigint
    references public.members(id) on delete set null,

  content text not null,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

drop trigger if exists trg_inquiries_updated_at on public.inquiries;

create trigger trg_inquiries_updated_at
before update on public.inquiries
for each row
execute function public.set_updated_at();

drop trigger if exists trg_inquiry_answers_updated_at on public.inquiry_answers;

create trigger trg_inquiry_answers_updated_at
before update on public.inquiry_answers
for each row
execute function public.set_updated_at();

create index if not exists idx_inquiries_member_created_at
on public.inquiries(member_id, created_at desc);

create index if not exists idx_inquiries_status_created_at
on public.inquiries(status, created_at desc);

create index if not exists idx_inquiries_category_status
on public.inquiries(category, status);

create index if not exists idx_inquiries_related_analysis_id
on public.inquiries(related_analysis_id);

create index if not exists idx_inquiry_answers_inquiry_created_at
on public.inquiry_answers(inquiry_id, created_at desc);

create index if not exists idx_inquiry_answers_admin_id
on public.inquiry_answers(admin_id);

alter table public.inquiries enable row level security;
alter table public.inquiry_answers enable row level security;

revoke all
on table public.inquiries
from anon, authenticated;

revoke all
on table public.inquiry_answers
from anon, authenticated;

revoke all
on sequence public.inquiries_id_seq
from anon, authenticated;

revoke all
on sequence public.inquiry_answers_id_seq
from anon, authenticated;
