-- =========================================-- Filtory 초기 DB 스키마-- public schema-- =========================================

-- updated_at 자동 갱신 함수
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
    end;
    $$ language plpgsql;
-- =========================================-- 1. 회원 테이블-- =========================================
create table if not exists public.members (
  id bigint generated by default as identity primary key,

  login_id varchar(20),
  email varchar(255) unique,
  password_hash text,

  nickname varchar(100),
  real_name varchar(100),
  phone varchar(50),
  profile_img_url text,

  role varchar(30) not null default 'user',
  active boolean not null default true,

  email_verified boolean not null default false,

  last_login_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  deleted_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint members_role_check check (role in ('user', 'admin')),
  constraint members_login_id_format_check
    check (login_id is null or login_id ~ '^[a-z0-9_.-]{4,20}$')
);

drop trigger if exists trg_members_updated_at on public.members;

create trigger trg_members_updated_at
before update on public.members
for each row
execute function public.set_updated_at();

create unique index if not exists idx_members_login_id_normalized_unique
on public.members (lower(btrim(login_id)))
where login_id is not null and btrim(login_id) <> '';
-- =========================================-- 2. 소셜 로그인 계정 연결 테이블-- =========================================

create table if not exists public.social_accounts (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,

  provider varchar(30) not null,
  social_id varchar(255) not null,

  social_email varchar(255),
  social_nickname varchar(100),
  profile_img_url text,

  connected_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint social_accounts_provider_check
    check (provider in ('kakao', 'naver', 'google')),

  constraint social_accounts_provider_social_id_unique
    unique (provider, social_id),

  constraint social_accounts_member_provider_unique
    unique (member_id, provider)
);

drop trigger if exists trg_social_accounts_updated_at on public.social_accounts;

create trigger trg_social_accounts_updated_at
before update on public.social_accounts
for each row
execute function public.set_updated_at();

-- =========================================-- 3. 비밀번호 재설정 토큰 테이블-- =========================================
create table if not exists public.password_reset_tokens (  
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,

  token_hash text not null unique,

  expires_at timestamp with time zone not null,
  used_at timestamp with time zone,

  request_ip varchar(100),
  user_agent text,

  created_at timestamp with time zone not null default now()
);


-- =========================================-- 4. 병원 정보 테이블-- =========================================
create table if not exists public.hospitals (
  id bigint generated by default as identity primary key,

  hospital_name varchar(255) not null,
  category varchar(30) not null,

  naver_place_url text,
  naver_place_id varchar(100),
  source_provider varchar(20),
  external_place_id varchar(100),
  kakao_place_url text,

  google_map_url text,
  google_place_id varchar(255),

  address text,
  road_address text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  phone varchar(50),
  homepage_url text,

  description text,
  treatment_items text,

  has_photos boolean not null default false,
  has_videos boolean not null default false,
  has_reservation_link boolean not null default false,

  google_registered boolean not null default false,
  english_name varchar(255),
  has_english_info boolean not null default false,
  has_english_reviews boolean not null default false,
  is_official_hospital boolean not null default false,
  official_source varchar(20),

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint hospitals_category_check
    check (category in ('dermatology', 'ophthalmology', 'dentistry'))
);

create unique index if not exists uq_hospitals_source_provider_external_place_id
on public.hospitals(source_provider, external_place_id)
where source_provider is not null and external_place_id is not null;

create index if not exists idx_hospitals_latitude_longitude
on public.hospitals(latitude, longitude)
where latitude is not null and longitude is not null;

drop trigger if exists trg_hospitals_updated_at on public.hospitals;

create trigger trg_hospitals_updated_at
before update on public.hospitals
for each row
execute function public.set_updated_at();
-- =========================================-- 5. 리뷰 테이블-- =========================================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,

  member_id bigint references public.members(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,

  review_original text not null,
  review_language varchar(20) not null default 'ko',

  review_translated_ko text,
  review_translated_en text,

  source_platform varchar(30) not null default 'user_input',

  created_at timestamp with time zone not null default now(),

  constraint reviews_language_check
    check (review_language in ('ko', 'en', 'unknown')),

  constraint reviews_source_platform_check
    check (source_platform in ('user_input', 'naver_place', 'google_map', 'manual'))
);


-- =========================================
-- 6. AI 분석 결과 테이블
-- =========================================
create table if not exists public.analysis_results (
  id bigint generated by default as identity primary key,

  member_id bigint references public.members(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  review_id bigint not null references public.reviews(id) on delete cascade,

  total_score int,
  trust_score int,
  ad_score int,
  place_score int,
  foreigner_score int,

  trust_level varchar(30),
  ad_suspicion varchar(30),
  repetition_suspicion varchar(30),

  summary_ko text,
  summary_en text,

  evidence_json jsonb,
  ai_model varchar(100),

  created_at timestamp with time zone not null default now(),

  constraint analysis_total_score_check
    check (total_score is null or (total_score >= 0 and total_score <= 100)),

  constraint analysis_trust_score_check
    check (trust_score is null or (trust_score >= 0 and trust_score <= 100)),

  constraint analysis_ad_score_check
    check (ad_score is null or (ad_score >= 0 and ad_score <= 100)),

  constraint analysis_place_score_check
    check (place_score is null or (place_score >= 0 and place_score <= 100)),

  constraint analysis_foreigner_score_check
    check (foreigner_score is null or (foreigner_score >= 0 and foreigner_score <= 100))
);



-- =========================================-- 7. 구독 플랜 테이블-- =========================================
create table if not exists public.subscription_plans (
  id bigint generated by default as identity primary key,

  plan_code varchar(30) not null unique,
  plan_name varchar(100) not null,

  monthly_price int not null default 0,
  monthly_analysis_limit int,

  description text,
  active boolean not null default true,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint subscription_plans_code_check
    check (plan_code in ('free', 'pro', 'business')),

  constraint subscription_plans_monthly_price_check
    check (monthly_price >= 0),

  constraint subscription_plans_monthly_analysis_limit_check
    check (monthly_analysis_limit is null or monthly_analysis_limit >= 0)
);

drop trigger if exists trg_subscription_plans_updated_at on public.subscription_plans;

create trigger trg_subscription_plans_updated_at
before update on public.subscription_plans
for each row
execute function public.set_updated_at();


-- =========================================
-- 8. 회원 구독 상태 테이블
-- =========================================
create table if not exists public.member_subscriptions (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,
  plan_id bigint not null references public.subscription_plans(id),

  status varchar(30) not null default 'active',

  started_at timestamp with time zone not null default now(),
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,

  cancel_at_period_end boolean not null default false,
  canceled_at timestamp with time zone,

  payment_provider varchar(30),
  payment_customer_id varchar(255),
  payment_subscription_id varchar(255),

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint member_subscriptions_status_check
    check (status in ('active', 'trialing', 'past_due', 'canceled', 'expired'))
);

drop trigger if exists trg_member_subscriptions_updated_at on public.member_subscriptions;

create trigger trg_member_subscriptions_updated_at
before update on public.member_subscriptions
for each row
execute function public.set_updated_at();


-- =========================================
-- 9. 기본 플랜 데이터
-- =========================================
insert into public.subscription_plans
(plan_code, plan_name, monthly_price, monthly_analysis_limit, description)
values
('free', '무료 플랜', 0, 5, '월 5회 리뷰 분석 가능'),
('pro', '프로 플랜', 9900, 100, '월 100회 리뷰 분석 가능'),
('business', '비즈니스 플랜', 29900, 500, '월 500회 리뷰 분석 가능')
on conflict (plan_code) do nothing;


-- =========================================
-- 10. 새 회원 가입 시 free 플랜 자동 부여 함수
-- =========================================
create or replace function public.create_default_free_subscription()
returns trigger as $$
declare
  free_plan_id bigint;
begin
  select id
  into free_plan_id
  from public.subscription_plans
  where plan_code = 'free'
  limit 1;

  if free_plan_id is not null then
    insert into public.member_subscriptions (
      member_id,
      plan_id,
      status,
      started_at,
      current_period_start,
      current_period_end
    )
    values (
      new.id,
      free_plan_id,
      'active',
      now(),
      date_trunc('month', now()),
      date_trunc('month', now()) + interval '1 month'
    );
  end if;

  return new;
end;
$$ language plpgsql;


drop trigger if exists trg_members_create_default_subscription
on public.members;

create trigger trg_members_create_default_subscription
after insert on public.members
for each row
execute function public.create_default_free_subscription();


-- =========================================
-- 11. 이미 존재하는 회원에게 free 플랜 부여
-- =========================================
insert into public.member_subscriptions (
  member_id,
  plan_id,
  status,
  started_at,
  current_period_start,
  current_period_end
)
select
  m.id,
  p.id,
  'active',
  now(),
  date_trunc('month', now()),
  date_trunc('month', now()) + interval '1 month'
from public.members m
join public.subscription_plans p
  on p.plan_code = 'free'
where not exists (
  select 1
  from public.member_subscriptions ms
  where ms.member_id = m.id
);


-- =========================================
-- 12. 조회 성능용 인덱스
-- =========================================

-- members
create index if not exists idx_members_email
on public.members(email);

-- social_accounts
create index if not exists idx_social_accounts_member_id
on public.social_accounts(member_id);

create index if not exists idx_social_accounts_provider_social_id
on public.social_accounts(provider, social_id);

-- password_reset_tokens
create index if not exists idx_password_reset_tokens_member_id
on public.password_reset_tokens(member_id);

create index if not exists idx_password_reset_tokens_token_hash
on public.password_reset_tokens(token_hash);

-- hospitals
create index if not exists idx_hospitals_category
on public.hospitals(category);

create index if not exists idx_hospitals_naver_place_id
on public.hospitals(naver_place_id);

create index if not exists idx_hospitals_google_place_id
on public.hospitals(google_place_id);

-- reviews
create index if not exists idx_reviews_member_id
on public.reviews(member_id);

create index if not exists idx_reviews_hospital_id
on public.reviews(hospital_id);

create index if not exists idx_reviews_created_at
on public.reviews(created_at);

-- analysis_results
create index if not exists idx_analysis_results_member_id
on public.analysis_results(member_id);

create index if not exists idx_analysis_results_hospital_id
on public.analysis_results(hospital_id);

create index if not exists idx_analysis_results_review_id
on public.analysis_results(review_id);

create index if not exists idx_analysis_results_created_at
on public.analysis_results(created_at);

-- subscription_plans
create index if not exists idx_subscription_plans_plan_code
on public.subscription_plans(plan_code);

-- member_subscriptions
create index if not exists idx_member_subscriptions_member_id
on public.member_subscriptions(member_id);

create index if not exists idx_member_subscriptions_plan_id
on public.member_subscriptions(plan_id);

create index if not exists idx_member_subscriptions_status
on public.member_subscriptions(status);

-- 한 회원이 동시에 active/trialing/past_due 구독을 여러 개 못 가지게 함
create unique index if not exists idx_member_subscriptions_one_active
on public.member_subscriptions(member_id)
where status in ('active', 'trialing', 'past_due');

alter table public.hospitals
add column if not exists operating_hours text,
add column if not exists reservation_url text,
add column if not exists naver_rating numeric(3,2),
add column if not exists naver_review_count int not null default 0,
add column if not exists google_rating numeric(3,2),
add column if not exists google_review_count int not null default 0,
add column if not exists has_google_photos boolean not null default false;

create unique index if not exists idx_hospitals_naver_place_id_unique
on public.hospitals(naver_place_id)
where naver_place_id is not null;

create unique index if not exists idx_hospitals_google_place_id_unique
on public.hospitals(google_place_id)
where google_place_id is not null;

-- =========================================
-- 13. 분석 요청 테이블
-- 분석 시작 버튼을 눌렀을 때 생성되는 "분석 1건" 단위
-- =========================================
create table if not exists public.analysis_requests (
  id bigint generated by default as identity primary key,

  member_id bigint references public.members(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,

  analysis_type varchar(30) not null default 'single_review',
  request_status varchar(30) not null default 'pending',

  input_language varchar(20) not null default 'ko',
  output_language varchar(20) not null default 'ko',

  review_count int not null default 0,

  request_options_json jsonb,
  error_message text,

  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by bigint references public.members(id) on delete set null,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint analysis_requests_type_check
    check (analysis_type in ('single_review', 'multi_review', 'place_only', 'full')),

  constraint analysis_requests_status_check
    check (request_status in ('pending', 'analyzing', 'success', 'failed', 'canceled')),

  constraint analysis_requests_input_language_check
    check (input_language in ('ko', 'en', 'unknown')),

  constraint analysis_requests_output_language_check
    check (output_language in ('ko', 'en')),

  constraint analysis_requests_review_count_check
    check (review_count >= 0)
);

drop trigger if exists trg_analysis_requests_updated_at on public.analysis_requests;

create trigger trg_analysis_requests_updated_at
before update on public.analysis_requests
for each row
execute function public.set_updated_at();


-- =========================================
-- 14. reviews에 analysis_request 연결 컬럼 추가
-- 한 분석 요청에 여러 리뷰가 들어갈 수 있게 함
-- =========================================
alter table public.reviews
add column if not exists request_id bigint
references public.analysis_requests(id) on delete cascade;


-- =========================================
-- 15. analysis_results에 analysis_request 연결 컬럼 추가
-- 최종 분석 결과를 분석 요청 1건에 연결
-- =========================================
alter table public.analysis_results
add column if not exists request_id bigint
references public.analysis_requests(id) on delete cascade;


-- 기존 analysis_results.review_id는 단일 리뷰 분석용으로만 쓰고,
-- 여러 리뷰 종합 분석에서는 null 허용
alter table public.analysis_results
alter column review_id drop not null;


-- 한 분석 요청에는 최종 분석 결과가 1개만 생기도록 제한
create unique index if not exists idx_analysis_results_request_id_unique
on public.analysis_results(request_id)
where request_id is not null;


-- =========================================
-- 16. 조회 성능용 인덱스
-- =========================================
create index if not exists idx_analysis_requests_member_id
on public.analysis_requests(member_id);

create index if not exists idx_analysis_requests_hospital_id
on public.analysis_requests(hospital_id);

create index if not exists idx_analysis_requests_status
on public.analysis_requests(request_status);

create index if not exists idx_analysis_requests_created_at
on public.analysis_requests(created_at);

create index if not exists idx_analysis_requests_completed_at
on public.analysis_requests(completed_at);

create index if not exists idx_analysis_requests_deleted_at
on public.analysis_requests(deleted_at);

create index if not exists idx_analysis_requests_member_deleted_at
on public.analysis_requests(member_id, deleted_at);

create index if not exists idx_reviews_request_id
on public.reviews(request_id);

create index if not exists idx_analysis_results_request_id
on public.analysis_results(request_id);

-- =========================================
-- 17. 관리자 작업 로그 테이블
-- =========================================
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,

  admin_member_id bigint references public.members(id) on delete set null,

  action_type varchar(50) not null,
  target_table varchar(50),
  target_id bigint,

  description text,
  before_json jsonb,
  after_json jsonb,

  request_ip varchar(100),
  user_agent text,

  created_at timestamp with time zone not null default now(),

  constraint admin_audit_logs_action_type_check
    check (action_type in (
      'member_update',
      'member_deactivate',
      'hospital_create',
      'hospital_update',
      'hospital_delete',
      'review_update',
      'review_delete',
      'analysis_review',
      'report_resolve',
      'subscription_update',
      'login'
    ))
);

create index if not exists idx_admin_audit_logs_admin_member_id
on public.admin_audit_logs(admin_member_id);

create index if not exists idx_admin_audit_logs_action_type
on public.admin_audit_logs(action_type);

create index if not exists idx_admin_audit_logs_target
on public.admin_audit_logs(target_table, target_id);

create index if not exists idx_admin_audit_logs_created_at
on public.admin_audit_logs(created_at);

-- =========================================
-- 18. 리뷰/분석 결과 신고 및 관리자 검토 테이블
-- =========================================
create table if not exists public.review_reports (
  id bigint generated by default as identity primary key,

  reporter_member_id bigint references public.members(id) on delete set null,

  hospital_id bigint references public.hospitals(id) on delete cascade,
  review_id bigint references public.reviews(id) on delete cascade,
  analysis_result_id bigint references public.analysis_results(id) on delete cascade,

  report_type varchar(50) not null,
  report_reason text,

  status varchar(30) not null default 'pending',

  admin_member_id bigint references public.members(id) on delete set null,
  admin_memo text,
  resolved_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint review_reports_type_check
    check (report_type in (
      'spam',
      'ad_suspicion',
      'inaccurate_analysis',
      'inappropriate_content',
      'wrong_hospital_info',
      'other'
    )),

  constraint review_reports_status_check
    check (status in ('pending', 'reviewing', 'resolved', 'rejected'))
);

drop trigger if exists trg_review_reports_updated_at on public.review_reports;

create trigger trg_review_reports_updated_at
before update on public.review_reports
for each row
execute function public.set_updated_at();

create index if not exists idx_review_reports_reporter_member_id
on public.review_reports(reporter_member_id);

create index if not exists idx_review_reports_admin_member_id
on public.review_reports(admin_member_id);

create index if not exists idx_review_reports_hospital_id
on public.review_reports(hospital_id);

create index if not exists idx_review_reports_review_id
on public.review_reports(review_id);

create index if not exists idx_review_reports_analysis_result_id
on public.review_reports(analysis_result_id);

create index if not exists idx_review_reports_status
on public.review_reports(status);

create index if not exists idx_review_reports_created_at
on public.review_reports(created_at);

-- =========================================
-- 19. 도움센터 / 1:1 문의 티켓 테이블
-- =========================================
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,

  category varchar(40) not null,
  sub_category varchar(120),
  title varchar(200) not null,
  content text not null,
  status varchar(30) not null default 'PENDING',

  related_analysis_id bigint references public.analysis_requests(id) on delete set null,
  attachment_url text,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint inquiries_category_check
    check (category in (
      'ANALYSIS_RESULT',
      'REVIEW_INPUT',
      'ACCOUNT',
      'PAYMENT',
      'SUGGESTION',
      'OTHER'
    )),

  constraint inquiries_status_check
    check (status in ('PENDING', 'IN_PROGRESS', 'ANSWERED'))
);

create table if not exists public.inquiry_answers (
  id bigint generated by default as identity primary key,

  inquiry_id bigint not null references public.inquiries(id) on delete cascade,
  admin_id bigint references public.members(id) on delete set null,
  content text not null,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

drop trigger if exists trg_inquiries_updated_at on public.inquiries;

create trigger trg_inquiries_updated_at
before update on public.inquiries
for each row
execute function public.set_updated_at();

drop trigger if exists trg_inquiry_answers_updated_at on public.inquiry_answers;

create trigger trg_inquiry_answers_updated_at
before update on public.inquiry_answers
for each row
execute function public.set_updated_at();

create index if not exists idx_inquiries_member_created_at
on public.inquiries(member_id, created_at desc);

create index if not exists idx_inquiries_status_created_at
on public.inquiries(status, created_at desc);

create index if not exists idx_inquiries_category_status
on public.inquiries(category, status);

create index if not exists idx_inquiries_related_analysis_id
on public.inquiries(related_analysis_id);

create index if not exists idx_inquiry_answers_inquiry_created_at
on public.inquiry_answers(inquiry_id, created_at desc);

create index if not exists idx_inquiry_answers_admin_id
on public.inquiry_answers(admin_id);


-- 1. 회원 전화번호
alter table public.members
add column if not exists phone varchar(30);

create index if not exists idx_members_phone
on public.members(phone)
where phone is not null;


-- 2. 병원 지역 필터용 컬럼
-- 예: 강남, 서초, 홍대, 명동 등
alter table public.hospitals
add column if not exists region varchar(100);

create index if not exists idx_hospitals_region
on public.hospitals(region)
where region is not null;

create index if not exists idx_hospitals_category_region
on public.hospitals(category, region)
where region is not null;


-- 3. 회원 약관 동의 기록 테이블
create table if not exists public.member_terms_agreements (
  id bigint generated by default as identity primary key,

  member_id bigint not null references public.members(id) on delete cascade,

  agreement_type varchar(30) not null,
  version varchar(50) not null default 'v1',

  agreed boolean not null default true,
  agreed_at timestamp with time zone not null default now(),

  revoked_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint member_terms_agreements_type_check
    check (agreement_type in ('terms', 'privacy', 'marketing')),

  constraint member_terms_agreements_member_type_version_unique
    unique (member_id, agreement_type, version)
);

drop trigger if exists trg_member_terms_agreements_updated_at
on public.member_terms_agreements;

create trigger trg_member_terms_agreements_updated_at
before update on public.member_terms_agreements
for each row
execute function public.set_updated_at();

create index if not exists idx_member_terms_agreements_member_id
on public.member_terms_agreements(member_id);

create index if not exists idx_member_terms_agreements_type
on public.member_terms_agreements(agreement_type);

commit;
