export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FIND_ID: "/find-id",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  AUTH_CALLBACK: "/auth/callback",
  VERIFY_EMAIL: "/verify-email",

  ANALYZE: "/analyze",
  RESULT: "/result",
  HISTORY: "/history",
  CHATBOT: "/chatbot",

  MYPAGE: "/mypage",
  MYPAGE_PROFILE: "/mypage/profile",
  MYPAGE_HISTORY: "/mypage/history",
  MYPAGE_SAVED: "/mypage/saved",
  MYPAGE_COMPARE: "/mypage/compare",
  MYPAGE_REPORTS: "/mypage/reports",
  MYPAGE_NOTIFICATIONS: "/mypage/notifications",
  MYPAGE_SETTINGS: "/mypage/settings",
  MYPAGE_SECURITY: "/mypage/security",
  MYPAGE_RECENT: "/mypage/recent",
  MYPAGE_INSIGHTS: "/mypage/insights",
  MYPAGE_DATA: "/mypage/data",
  MYPAGE_WITHDRAWAL: "/mypage/withdrawal",

  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_HOSPITALS: "/admin/hospitals",
} as const;
