export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FIND_ID: "/find-id",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  AUTH_CALLBACK: "/auth/callback",
  VERIFY_EMAIL: "/verify-email",

  ANALYZE: "/analyze",
  RESULT: "/result",
  HISTORY: "/history",
  HISTORY_TRASH: "/history/trash",
  CHATBOT: "/chatbot",

  HELP: "/help",
  HELP_NEW: "/help/new",
  HELP_MY: "/help/my",
  NOTICES: "/notices",

  MYPAGE: "/mypage",
  MYPAGE_PROFILE: "/mypage/profile",
  MYPAGE_HISTORY: "/mypage/history",
  MYPAGE_SAVED: "/mypage/favorite-hospitals",
  MYPAGE_FAVORITE_HOSPITALS: "/mypage/favorite-hospitals",
  MYPAGE_REPORTS: "/mypage/reports",
  MYPAGE_NOTIFICATIONS: "/mypage/notifications",
  MYPAGE_SETTINGS: "/mypage/settings",
  MYPAGE_MEMBERSHIP: "/mypage/membership",
  MYPAGE_CHATBOT_HISTORY: "/mypage/chatbot-history",
  MYPAGE_SECURITY: "/mypage/security",
  MYPAGE_RECENT: "/mypage/recent",
  MYPAGE_INSIGHTS: "/mypage/insights",
  MYPAGE_DATA: "/mypage/data",
  MYPAGE_WITHDRAWAL: "/mypage/withdrawal",
  MYPAGE_TERMS: "/mypage/terms",
  MYPAGE_PRIVACY: "/mypage/privacy",
  MYPAGE_VERSION: "/mypage/app-version",

  ADMIN: "/admin",
  UNAUTHORIZED: "/unauthorized",
  ADMIN_USERS: "/admin/users",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_HOSPITALS: "/admin/hospitals",
  ADMIN_INQUIRIES: "/admin/inquiries",
  ADMIN_USAGE: "/admin/usage",
  ADMIN_MEMBERSHIPS: "/admin/memberships",
  ADMIN_AD_REWARDS: "/admin/ad-rewards",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_ANALYSES: "/admin/analyses",
  ADMIN_ERRORS: "/admin/errors",
  ADMIN_SUPPORT: "/admin/support",
  ADMIN_NOTICES: "/admin/notices",
  ADMIN_SYSTEM: "/admin/system",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
  HOSPITAL_DETAIL: "/hospitals",
} as const;
